version: '2.1'

services:
  # ------------------------------------------------------------------------------------
  # Fake data generators over MQTT
  # ------------------------------------------------------------------------------------
  data-generators:
    build:
      context: .
      dockerfile: generator_simulator/Dockerfile.template
    environment:
      - GENERATORS=3
      - BROKER=hivemq4
    depends_on:
      - hivemq4
  
  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    build: ./node-red 
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
    ports:
        - 80:80
    environment:
        PORT: 80
        USERNAME: "balena"
        PASSWORD: "balena"
        ENCRIPTION_KEY: "balena"        
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"

  # ------------------------------------------------------------------------------------
  # Influxdb
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    restart: unless-stopped
    ports:
        - '8086'
    volumes:
        - influxdb-data:/var/lib/influxdb
        - influxdb-etc:/etc/influxdb

  # ------------------------------------------------------------------------------------
  # Grafana
  # ------------------------------------------------------------------------------------
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:8080'
    volumes:
        - "grafana-data:/data"

  # ------------------------------------------------------------------------------------
  # HiveMQ 4 MQTT broker
  # ------------------------------------------------------------------------------------
  hivemq4:
    #image: hivemq/hivemq4:latest
    build: ./hivemq4
    ports:
      - 1883:1883 # MQTT/TCP protocol port
      - 18080:8080 # Control Center port
      - 8000:8000 # Websockets port
    volumes:
      - hivemq_data:/opt/hivemq/data                     # Make broker data persistent throughout stop/start cycles
      - hivemq_log:/opt/hivemq/log                       # Persist log data
      - hivemq_license:/opt/hivemq/license               # Persist HiveMQ license
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"
  
  #ignition:
  #  image: inductiveautomation/ignition:latest
  #  ports:
  #    - 9088:8088
  
  #fuxa:

volumes:
  hivemq_data:
  hivemq_log:
  hivemq_license:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-etc:


